const RECORDS = [
  {
    id: 1,
    accountId: 'vuong.tuananh',
    firstName: 'Anh',
    lastName: 'Vuong Tuan',
    company: 'FPT Software',
    date: '01/01/2020',
    time: '12:30',
    temperature: 36.5,
  },
  {
    id: 2,
    accountId: 'vuong.tuananh',
    firstName: 'Anh',
    lastName: 'Vuong Tuan',
    company: 'FPT Software',
    date: '01/01/2020',
    time: '12:30',
    temperature: 36.5,
  },
  {
    id: 3,
    accountId: 'vuong.tuananh',
    firstName: 'Anh',
    lastName: 'Vuong Tuan',
    company: 'FPT Software',
    date: '01/01/2020',
    time: '12:30',
    temperature: 36.5,
  },
  {
    id: 4,
    accountId: 'vuong.tuananh',
    firstName: 'Anh',
    lastName: 'Vuong Tuan',
    company: 'FPT Software',
    date: '01/01/2020',
    time: '12:30',
    temperature: 36.5,
  },
  {
    id: 5,
    accountId: 'vuong.tuananh',
    firstName: 'Anh',
    lastName: 'Vuong Tuan',
    company: 'FPT Software',
    date: '01/01/2020',
    time: '12:30',
    temperature: 36.5,
  },
];

export default RECORDS;
